### ISSUE TITLE
0x1C2 no longer has 0xE or 0xC partition type

### ISSUE THREAD

**Issue by codernavi18** [bztsrc/raspi3-tutorial#102]
I am trying to develop my FAT32 disk image. But the `0x1C2` remains set to 0. In the raspbian FAT image, this is perfectly set to 0xE. 

Are there any recent changes in FAT filesystem as why this byte at `0x1C2` is no longer set? How did you prepare the disk image?

Below is my hexdump of a FAT file with above steps : 
```
naveen@workstation:/tmp$ dd if=/dev/zero of=disk.img bs=512 count=100
100+0 records in
100+0 records out
51200 bytes (51 kB, 50 KiB) copied, 0.0009233 s, 55.5 MB/s
naveen@workstation:/tmp$ fdisk disk.img

Welcome to fdisk (util-linux 2.34).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0xcd3d9803.

Command (m for help): n
Partition type
   p   primary (0 primary, 0 extended, 4 free)
   e   extended (container for logical partitions)
Select (default p): p
Partition number (1-4, default 1):
First sector (1-99, default 1):
Last sector, +/-sectors or +/-size{K,M,G,T,P} (1-99, default 99):

Created a new partition 1 of type 'Linux' and of size 49.5 KiB.

Command (m for help): c
DOS Compatibility flag is set (DEPRECATED!)

Command (m for help): t
Selected partition 1
Hex code (type L to list all codes): c
Changed type of partition 'Linux' to 'W95 FAT32 (LBA)'.

Command (m for help): w
The partition table has been altered.
Syncing disks.

naveen@workstation:/tmp$ mkfs.fat disk.img
mkfs.fat 4.1 (2017-01-24)
naveen@workstation:/tmp$ hexdump -C disk.img
00000000  eb 3c 90 6d 6b 66 73 2e  66 61 74 00 02 04 01 00  |.<.mkfs.fat.....|
00000010  02 00 02 64 00 f8 01 00  20 00 40 00 00 00 00 00  |...d.... .@.....|
00000020  00 00 00 00 80 00 29 ed  89 67 3c 4e 4f 20 4e 41  |......)..g<NO NA|
00000030  4d 45 20 20 20 20 46 41  54 31 32 20 20 20 0e 1f  |ME    FAT12   ..|
00000040  be 5b 7c ac 22 c0 74 0b  56 b4 0e bb 07 00 cd 10  |.[|.".t.V.......|
00000050  5e eb f0 32 e4 cd 16 cd  19 eb fe 54 68 69 73 20  |^..2.......This |
00000060  69 73 20 6e 6f 74 20 61  20 62 6f 6f 74 61 62 6c  |is not a bootabl|
00000070  65 20 64 69 73 6b 2e 20  20 50 6c 65 61 73 65 20  |e disk.  Please |
00000080  69 6e 73 65 72 74 20 61  20 62 6f 6f 74 61 62 6c  |insert a bootabl|
00000090  65 20 66 6c 6f 70 70 79  20 61 6e 64 0d 0a 70 72  |e floppy and..pr|
000000a0  65 73 73 20 61 6e 79 20  6b 65 79 20 74 6f 20 74  |ess any key to t|
000000b0  72 79 20 61 67 61 69 6e  20 2e 2e 2e 20 0d 0a 00  |ry again ... ...|
000000c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 55 aa  |..............U.|
00000200  f8 ff ff 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000210  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000400  f8 ff ff 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000410  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
0000c800
```

**Comment by bztsrc** [comment]
> Are there any recent changes in FAT filesystem as why this byte at 0x1C2 is no longer set?

No. The file system on a partition has nothing to do with the MBR tables, those have to be set independently (this was always like this, so no change here).

Long story short, what you're doing is a single file system image. That alone won't work, because on a typical drive you can have multiple file systems, each in its own partition. So the very first sector of a drive is not a VBR (Volume boot record, the first sector of a FAT file system), rather an MBR (Master boot record) with a partitioning table. There each partition has a type, a first sector address and a number of sectors field. The file system only occupies the area pointed by that partition table entry, it is the first sector of the partition that should have the VBR.

If you're on Linux, then you can use the `fdisk` command to create a partitioning table and set the file system type of a partition for example. Then you can set up a loopback device which points inside that disk image to the desired partition area, and then you can use mkfs.vfat to create a file system on that loopback device. See more details [here](https://wiki.osdev.org/Bootable_Disk) (note: this tutorial creates a GPT table, you'll need an MBR table, so do not use the `g` command, rather use the `o` command).

If you want to do this programmatically, [here](https://gitlab.com/bztsrc/bootboot/-/blob/master/aarch64-rpi/mkboot.c) is a little a tool I wrote that locates the ESP in GPT and then mirrors it into the MBR partitioning table. You can skip the GPT part, just take a look at the MBR part. But you'll still have to create and add the partition image.

Cheers,
bzt

**Comment by bztsrc** [comment]
Maybe I wasn't clear, when you do
```
naveen@workstation:/tmp$ mkfs.fat disk.img
```
That will overwrite whatever you have in the img file with a single file system. What you need is, set up a loopback device which points inside the disk.img, and then use
```
naveen@workstation:/tmp$ mkfs.fat /dev/loop0
```

One more thing to keep in mind: your image is just 51Kb. You cannot create a valid FAT32 on that. FAT file system has a minimum storage space requirement of 33Mb. See [size limits](https://en.wikipedia.org/wiki/Design_of_the_FAT_file_system#Size_limits). I suggest to use FAT16 (RPi firmware can handle that too just fine), `mkfs.fat -F 16`. The minimum size for FAT16 is just 2Mb.

Cheers,
bzt
