### ISSUE TITLE
0A PCScreenFont only works in QEMU

### ISSUE THREAD

**Issue by firestar4204** [bztsrc/raspi3-tutorial#107]
Title.  The text only works in qemu, and when I put the same image into my raspberry pi, blank screen.  I tried with the Homer image *and* the text at the same time, the text shows up in qemu but not on the pi.  The image shows up on both.  With your kernel8.img, text works, but for some reason mine doesn't work.  I'm stumped.

**Comment by bztsrc** [comment]
> With your kernel8.img, text works, but for some reason mine doesn't work.

Then the issue must be in your code. I'd have to take a look at your code to tell more, but one of the most likely scenario is, your data isn't aligned properly. Qemu is very forgiving about alignment issues, but the real hardware isn't.

Hope this helps,
bzt

**Comment by firestar4204** [comment]
Thanks.  I'll take a look sometime

**Comment by bztsrc** [comment]
Ok! Let me know if you have any more questions, I'll try to answer.

Cheers,
bzt

**Comment by firestar4204** [comment]
might this offer more insight?
https://termbin.com/sli9

**Comment by firestar4204** [comment]
@bztsrc I have a compile output here, I think it has something to do with these warnings, but I don't know how to fix them. https://termbin.com/sli9

**Comment by bztsrc** [comment]
Sorry for the delay, I was rather busy lately!

There's no trivial problem in your code that I can see. This must be an alignment issue. Try adding alignment to the linker script:
```
.rodata : { . = ALIGN(16); *(.rodata .rodata.* .gnu.linkonce.r*) }
```
> I think it has something to do with these warnings

Nope, that's just because the imported symbol has no real size, it is 1 byte according to the compiler, but we know better and we cast it to some struct that's bigger than 1 byte. You can change the definition to
```c
extern volatile unsigned char _binary_font_psf_start[whatever the actual size is in bytes];
```
and reference as `&_binary_font_psf_start[0]`. BTW, you don't need both the psf and the sfn font, only one. You can decide which one, psf is simpler but does not support full UNICODE, while sfn is a bit trickier to unpack, but much smaller and supports proportional fonts and UTF-8 out-of-the-box, so full UNICODE.

Further advice: try adding the exception handler from tutorial [11](https://github.com/bztsrc/raspi3-tutorial/blob/master/11_exceptions/exc.c). You'll need a little bit of Assembly too from [start.S](https://github.com/bztsrc/raspi3-tutorial/blob/master/11_exceptions/start.S) (makes sure you're running as supervisor and sets up _vectors callbacks which in turn call `exc_handler` in C). That way you'll see what's the issue on real HW.

You might want to go ahead and add virtual memory too. It seems like a big fuzz, but with the MMU turned on, no misaligned exceptions will be raised at all, so worth it. And sooner or later you'll need virtual memory anyway.

Hope this helps,
bzt

**Comment by firestar4204** [comment]
Thanks for the help! I understand your position of being busy.  I’ll edit the code when I have the chance.
