### ISSUE TITLE
Segmentation fault on execution of 09_framebuffer and 0A_pcscreenfont

### ISSUE THREAD

**Issue by afaq1182** [bztsrc/raspi3-tutorial#111]
whenever I execute kernel8.img on my qemu with the command

`qemu-system-aarch64 -M raspi3b -kernel /kernel8.img -serial stdio`

there is an error on my terminal saying segmentation fault. Do you suggest any fix?

This only happens on the two tutorials of display on the screen. Qemu is blank on all the chapters but I understand that those tutorials aren't meant to display anything on the screen. Please guide me to fix this error.

**Comment by bztsrc** [comment]
Huh, that's strange. This tutorial was written years ago, hasn't changed for a long time and surely was working. It might be that the issue is with your qemu (compiled with non-standard options or has a non-standard config or something like that).

> there is an error on my terminal saying segmentation fault. Do you suggest any fix?

Please try running with `-d int` to see what exception happens and where. I can't suggest a fix unless I know exactly which line of code causes the issue.

Cheers,
bzt

**Comment by bztsrc** [comment]
FYI, "segmentation fault" is just a catch up phrase for all CPU generated exceptions. It isn't clear that it refers to the qemu's code or the emulated CPU for example. So it could mean that the issue is actually in qemu itself, we can't rule that out yet. If `-d int` does not print anything, then try a different qemu version, IMHO.

Cheers,
bzt

**Comment by afaq1182** [comment]
yes `-d int` does not show anything so I guess it's problem with qemu. I also copied the kernel8.img file in the repo (I didn't compile it myself) to the boot partition in sd card and inserted in my raspberry pi 3B, it is a blank screen there too. I am using HDMI cable on raspberry to connect to my monitor with the following config

`hdmi_safe=1
 hdmi_mode=16
 config_hdmi_boost=7
 dtoverlay=vc4-kms-v3d
 arm64-bit=1
 ramebuffer_priority=2
 enable_uart=1
 uart_2ndstage=1 `

I hope that helps.

**Comment by afaq1182** [comment]
also what do you suggest I do? install some old version of qemu? what can I do to run this program with an HDMI port?

**Comment by bztsrc** [comment]
> I guess it's problem with qemu

No need to guess, it surely is, valgrind said so.

>  am using HDMI cable on raspberry to connect to my monitor with the following config

I've just tested it on Rpi3b, and it works for me. No config.txt at all, everything left at factory defaults, and it works.

Cheers,
bzt
