### ISSUE TITLE
Emulating the file system tutorials

### ISSUE THREAD

**Issue by OllieLollie1** [bztsrc/raspi3-tutorial#15]
Would you please explain what you mean by saying 
qemu-system-aarch64 -M raspi3 -drive file=$(yourimagefile),if=sd,format=raw -serial stdio
for the file system tutorials because I don't understand what you mean by $(yourimagefile)

**Comment by bztsrc** [comment]
Substitute with the filename of your disk image you've created. For example, you could download the raspbian image and rename it rpi-tutorials.dd, then mount it's first partition on a loopback device (read the manual page losetup, you'll have to add the file offset of the first partition). In that case you should use "-drive file=rpi-tutorials.dd,if=sd,format=raw" with qemu.
Example (assuming the first partition starts as sector 2048, use fdisk p to get the exact value):
fdisk rpi-tutorials.dd       (inside fdisk cli, use the command p to list the partitions)
losetup -o $[2048*512] rpi-tutorials.dd /dev/loop0
mount -o loop /dev/loop0 /mnt/rpidisk
Now you will see the contents of the raspberry boot partition under /mnt/rpidisk. You can copy kernel8.img there, then
umount /mnt/rpidisk
losetup -d /dev/loop0
After that you can write the .dd image on an SD card with the dd command, or use it with qemu (although qemu won't be able to locate kernel8.img inside the disk image, because it does not emulate the GPU boot up sequence. So you'll have to specify your local kernel8.img file with -kernel option too along with "-drive".)
If you are more exprenced with disk images, and you don't want to use raspbian image, you can create one with: dd, fdisk, mkfs.vfat and mount that using the commands above.
Mounting loopback devices require root privileges. If you are not running them as root, prefix the commands with "sudo".

Cheers,
bzt
