### ISSUE TITLE
0E_initrd

### ISSUE THREAD

**Issue by EitanSomething** [bztsrc/raspi3-tutorial#44]
When I run the Makefile in 0E_initrd I get the error  `make: *** No rule to make target 'ramdisk', needed by 'rd.o'.  Stop.`What am  I doing wrong?

**Comment by bztsrc** [comment]
There's no rule for 'ramdisk', because it's supposed to be provided by you. For testing purposes, as the [readme](https://github.com/bztsrc/raspi3-tutorial/tree/master/0E_initrd#makefile) says, you can use:
```
make tar
```
or
```
make cpio
```
to create an example ramdisk with a few files in it. The compiled code can parse both tar and cpio just as-is, but on creation you must choose which one to create (assuming you don't have your own ramdisk already).

Cheers,
bzt
