### ISSUE TITLE
Not showing anything on serial port 

### ISSUE THREAD

**Issue by btauro** [bztsrc/raspi3-tutorial#5]
The screen is blank when using terminal emulator with Rapberry Pi3. Not sure why this is happening.
Previous Tutorials with UART 0 have worked.But this tutorial for some reason does not print anything to the console,I suppose something to do with start.S.Not Sure.Could you help me with this

**Comment by bztsrc** [comment]
Okay, first thing first, which tutorial are you talking about?
If I understand right, the UART1 tutorials (1-4) were okay, and there was at least one (or more?) with UART0 (>4) that worked?

**Comment by btauro** [comment]
Hey,
1] All tutorials  before 0F_executionlevel have worked.
2]It is minicom terminal emulator
3] Yes it is set to 115200,8n1
4]I am using the recent commit

**Comment by bztsrc** [comment]
Thank you for the feedback, I'll look into that!

**Comment by bztsrc** [comment]
Hi btauro,

Bad news, I'm afraid. It turned out that my first test failed because of a sync error. I've compared the code in the tutorial with my original code, and there was only one difference, setting the virtual mpidr register. I've tested with and without it, both worked.
Since I'm unable to reproduce your error, I'm not sure what the problem could be. I've attached a screenshot, first I've tried my original code, then the tutorial with vmpidr code, then the unmodified tutorial. Finally I've tested the unmodified tutorial again, just to be sure.

Cheers,
bzt
![minicom](https://user-images.githubusercontent.com/12779069/35099967-4d824e24-fc5a-11e7-93a1-b15df3b095b7.png)

**Comment by btauro** [comment]
Could you share your config.txt with me i guess this may be the cause.

This is my config.txt
arm_control=0x200               
kernel_old=1
disable_commandline_tags=1
My qemu Output
![screenshot from 2018-01-19 13-19-52](https://user-images.githubusercontent.com/35237883/35167516-81f7d5a4-fd1b-11e7-8c58-a80cadebbeb4.png)

Unfortunately not working on Raspberry Pi3 for some reason

Do i require any additional files on my sd card.These are the files on my SD card
bootcode.bin
config.txt
start.elf
kernel8.img
fixup.dat

![screenshot from 2018-01-19 13-24-03](https://user-images.githubusercontent.com/35237883/35167757-405f0562-fd1c-11e7-908d-8121bb5e537b.png)
