### ISSUE TITLE
Memory Location Disparity Between Broadcom Datasheet and Tutorial

### ISSUE THREAD

**Issue by deef0000dragon1** [bztsrc/raspi3-tutorial#50]
Im attempting to get a project working with bare metal GPIO so that I have the tightest control possible, however, I am running into issues that I am having a hard time diagnosing because of the differences between documentation. 

The BCM2837 is apparently identical to the 36, which is also identical to the 35, however, the 2835 documentation at https://www.raspberrypi.org/app/uploads/2012/02/BCM2835-ARM-Peripherals.pdf lists the GPIO as 0x7E200000 while this tutorial lists 0x3F200000 for the GPIO. 

Right now I just want to turn _any_ pin on and off for proof of concept so that I can make sure my environment is working but I am having trouble. 

My test code. 
```
#define GPSET0 (volatile long *)0x3F20001C //GPIO  Pins 0-31     Pin Output Set 0 32 W
#define GPCLR0 (volatile long *)0x3F200028 //GPIO  Pins 0-31     Pin Output Clear 0 32 W

#define GPFSEL0 (volatile long *)0x3F200000 //GPIO Function Select 0 32 R/W 0-9
#define GPFSEL1 (volatile long *)0x3F200004 //GPIO Function Select 1 32 R/W 10-19
#define GPFSEL2 (volatile long *)0x3F200008 //GPIO Function Select 2 32 R/W 20-29

void main()
{

    //SetGPIOFunc(18, FuncOut);

    *GPFSEL0 = 0X9249249;
    *GPFSEL1 = 0X9249249;
    *GPFSEL2 = 0X9249249;

    while (1)
    {
        *GPSET0 = 0xffffffff;
        *GPCLR0 = 0xffffffff;

    }
}
```

**Comment by bztsrc** [comment]
Hi,

The address is correct. I've used that on qemu and on real machine, so I'm sure. Btw address starting with 7 suggests highest bit set, which means it's a GPU address. The same memory location has two addresses, one for the ARM CPU, and one for the GPU. This is why we have to mask the framebuffer address in order to access the lfb (see 09_framebuffer).

Yes, the documentation is not the best. Always read the errata (also included on their github page).

Your code is not okay. You have to configure the GPIO first (connect/disconnect pheripherals to pins, set up out direction, flush the configuration etc.). To give you an example: https://github.com/bztsrc/raspi3-tutorial/blob/master/05_uart0/uart.c#L61
Here I connect the PL011 chip to GPIO pins 14/15. This means if you want to toggle a GPIO pin on your own, make sure that it's free to use (not VCC, GND or used by some pheriperal like UART, SPI, I2C, PWM, CLOCK etc.), or choose an "alt" which makes it free (read more about alternate functions: https://elinux.org/RPi_BCM2835_GPIOs). Once you have your desired pin, set it to "out" direction, and don't forget to "flush" your new configuration.

I suggest to search the raspberrypi.org/forums for detailed instructions on how to toggle a GIPO pin. There are plenty of examples and step-by-step howtos, because lots of people were asking for this. Bare metal category has some Assembly examples which are trivial to convert to C because they are very simple. There are also links to complete GPIO C/C++ libraries (one pops into my mind, [rst's Circle C++ lib](https://github.com/rsta2/circle64/blob/master/lib/gpiopin.cpp), but there are plenty others).

Cheers,
bzt
