### ISSUE TITLE
RBIN64

### ISSUE THREAD

**Issue by yikuoyansui** [bztsrc/raspi3-tutorial#53]
Hi,

When I use "qemu-system-aarch64 -M raspi3 -kernel kernel8.img -serial stdio" to do the emulation, it was stuck in "RBIN64" and the screen of 'QEMU' is black. I expected to see the boot initialization and  then login on the terminal that shows on my host terminal. What should I do to achieve that?

**Comment by bztsrc** [comment]
Hi,

That's a serial boot loader. When you see "RBIN64" then it's waiting for a kernel over the serial line. For the kernel sender see the tutorial's README.md, there's a C++ version and a Java version too. I've also modified the [raspbootcom](https://gitlab.com/bztsrc/bootboot/blob/master/aarch64-rpi/raspbootcom.c) to compile as plain C under Linux. Those should be run on your PC connected to the RPi with a serial cable. 

When using qemu that way, then you can send the kernel to the terminal's ptty device instead of /dev/ttyUSB0, as the guest has it's serial port connected to it. The raspbootcom utility should work with a ptty device out-of-the-box, but you can write a simple sender in C yourself, the protocol is pretty simple:
1. open /dev/pts/X (where X is the terminal's number running qemu, use "lsof|grep qemu|grep /dev/pts" to find out)
2. write the kernel's size in a 32 bit little endian integer (4 bytes) to fd
3. read two bytes from fd. These can be either "OK" or "SE" for size error
4. write the kernel to fd
5. close the fd

Run that when you see the "RBIN64". That's all!

Cheers,
bzt
