### ISSUE TITLE
09_framebuffer - Color Channel Mapping

### ISSUE THREAD

**Issue by walkercam** [bztsrc/raspi3-tutorial#54]
I have compiled and run this tutorial on physical hardware and it works well however Homer is a shade of blue. It turns out the framebuffer maps the red and blue channels differently to how GIMP saves the header file. To have the image display with the correct color mapping it is necessary to swap pixel[0] and pixel [2] in homer.h.

#define HEADER_PIXEL(data,pixel) {\
pixel[2] = (((data[0] - 33) << 2) | ((data[1] - 33) >> 4)); \
pixel[1] = ((((data[1] - 33) & 0xF) << 4) | ((data[2] - 33) >> 2)); \
pixel[0] = ((((data[2] - 33) & 0x3) << 6) | ((data[3] - 33))); \
data += 4; \
}

**Comment by bztsrc** [comment]
Hi,

Thank you for your comment! Actually this was semi-intentional. First I made that mistake, because qemu does not emulate the VC correctly, then I've decided to left it there wondering if anybody notices :-) I've only fixed this in my bootloader.

You can't change the HEADER_PIXEL macro in homer.h, because that's a generated file. Instead on real hardware the order of the channels is configurable, see https://github.com/bztsrc/raspi3-tutorial/blob/master/09_framebuffer/lfb.c#L64
If you change the value for the 0x48006 tag, you can "swap" the red and blue channels to match the ordering of HEADER_PIXEL.

Cheers,
bzt
