### ISSUE TITLE
raspbootin64: stopping slave cores prevents SMP use

### ISSUE THREAD

**Issue by mrvn** [bztsrc/raspi3-tutorial#78]
In start.S you stop all slave cores using

    1: wfe
       b 1b

But that code is at address 0x800xx because you haven't relocated out of the way yet. So later, when the kernel is overloaded that code gets overwritten. If any core receives an event it will start executing the kernel but not from the start symbol.

Not being at the start symbol also makes it impossible to wake the core up intentionally in the kernel. I think start.S should write the opcode for `wfe` just before _start and jump there. It should also use x4 to detect the cpu id so x0-3 retain their original contents. Once the kernel is loaded the cores can be intentionally woken up.

**Comment by bztsrc** [comment]
Thank you, you're absolutely correct!

I haven't noticed this because the RPi firmware has changed https://github.com/raspberrypi/tools/blob/master/armstubs/armstub8.S and it now stops all APs by default. You have to write a function's address to "spin_cpuX" (at 0xd8) to wake them up. Regardless I should fix this, thank you very much for letting me know!

Cheers,
bzt
