### ISSUE TITLE
For compiling on OSX

### ISSUE THREAD

**Issue by powerhouseofthecell** [bztsrc/raspi3-tutorial#81]
Awesome tutorials! Thank you so much for putting this together (and having such clear explanations). 

I just wanted to throw out that if you're looking to compile the toolchain on OSX you can actually use Sergio Benitez's Homebrew solution [here](https://github.com/SergioBenitez/homebrew-osxct):
```
brew tap SergioBenitez/osxct
brew install aarch64-none-elf
```

(And of course readers can alias if they'd like to match the tutorial exactly)

**Comment by bztsrc** [comment]
Thank you, this is very useful, really good to know!

However I deliberately haven't listed precompiled solutions and packages for the cross-compiler. If I'm about to put a MacOS solution on the readme, then I'd have to put Windows and Linux solutions as well, and believe me, that would be a very very long list (linaro, port, pkgsrc, emerge, msys2, cygwin, deb, rpm, aur, etc. etc. etc.). That's why I pointed everybody to an appropriate dev forum for their OS instead to get the cross-compiler.

Cheers,
bzt
