### ISSUE TITLE
Any suggestions on how to get this working?

### ISSUE THREAD

**Issue by richstokes** [bztsrc/raspi3-tutorial#83]
MacOS host,

I am getting:

```
qemu-system-aarch64 -M raspi3 -kernel kernel8.img -drive file=2020-02-13-raspbian-buster.img,if=sd,format=raw -serial stdio -serial null -serial stdio
qemu-system-aarch64: -serial stdio: cannot use stdio by multiple character devices
qemu-system-aarch64: -serial stdio: could not connect serial device to character backend 'stdio'
```

I'm not sure what I'm missing here. If i just use `-serial stdio` it seems to start, but nothing is outputted/displayed.

Same with `qemu-system-aarch64 -M raspi3 -kernel kernel8.img -drive file=2020-02-13-raspbian-buster.img,if=sd,format=raw -serial null -serial stdio` -- no output at all

**Comment by bztsrc** [comment]
Hi,

> I'm not sure what I'm missing here.

You have three "-serial" arguments, two of which redirected to the same output. That won't work.

> no output at all

That depends which UART chip is used. For tutorials 1-4, which use the MINI AUX chip (UART1), you have to use exactly two "-serial" arguments, the first being null. This redirects the first UART0 to null, and the second one (UART1) to the terminal.

For tutorials 5 and above, which use the PL011 chip (UART0), you must specify exactly one "-serial" argument.

My advice is, use
```sh
make run
```
in each directory, that has the correct number of "-serial" arguments. For example, [03_uart1](https://github.com/bztsrc/raspi3-tutorial/blob/master/03_uart1/Makefile.gcc#L46) has two, because it's using the second UART chip. On the other hand, [05_uart0](https://github.com/bztsrc/raspi3-tutorial/blob/master/05_uart0/Makefile.gcc#L46) has only one, because it redirects the first UART chip.

On a real board, there's no difference, as both the MINI AUX and PL011 is properly configured for the same GPIO pins 14/15.

Cheers,
bzt
