### ISSUE TITLE
Emulating the raspi 3 on jetson nano failed with a black screen.

### ISSUE THREAD

**Issue by Marietto2008** [bztsrc/raspi3-tutorial#86]
Hello.

I'm on jetson nano and I'm trying to emulate the raspberry pi 3 cpu with a qcow2 image that I have created based on the raspberry bullseye. This is the version of my qemu-system-aarch64 :

QEMU emulator version 5.0.0 (-dirty)

this is the command that I use to start it :

qemu-system-aarch64 -M raspi3 -kernel /home/zi/Desktop/Work/I9/Arm32/raspberrypi-kernel_1.20210303-1_armhf/Data/boot/kernel8.img -drive file=/home/zi/Desktop/Work/Elements/OS/Raspy/Debian/hda-bullseye2.qcow2,if=sd,format=raw -serial stdio

what happens ? nothing. I see a black screen. Can u give some suggestion to unfreeze it ? thanks.

**Comment by bztsrc** [comment]
Hi

Depending on what's in kernel.img, this might be the correct behaviour. It might only send something to the UART, in which case you'll only see a black screen (and output in the terminal). Tutorials before the 09_framebuffer do not touch the screen at all. And tutorials before 05_uart0 write to the UART1, meaning if you want to see anything, use two "-serial" argument, like
```sh
qemu-system-aarch64 -M raspi3 -kernel /home/zi/Desktop/Work/I9/Arm32/raspberrypi-kernel_1.20210303-1_armhf/Data/boot/kernel8.img -drive file=/home/zi/Desktop/Work/Elements/OS/Raspy/Debian/hda-bullseye2.qcow2,if=sd,format=raw -serial null -serial stdio
```

Otherwise add "-S -s" to the command line, and attach a gdb to the VM. That way you can see and debug what's going on. A simpler solution would be to add "-d in_asm", which outputs each executed instruction, however that will generate a huge output log for sure, and you can't debug just follow the execution.

Cheers,
bzt
