### ISSUE TITLE
Why  *EMMC_INTERRUPT=*EMMC_INTERRUPT; in sd.c?

### ISSUE THREAD

**Issue by blippy** [bztsrc/raspi3-tutorial#94]
In line 156 of sd.c https://github.com/bztsrc/raspi3-tutorial/blob/master/0C_directory/sd.c 
you write
`*EMMC_INTERRUPT=*EMMC_INTERRUPT; *EMMC_ARG1=arg; *EMMC_CMDTM=code;
`

Can I ask what is the point of
`
*EMMC_INTERRUPT=*EMMC_INTERRUPT;
`
It seems like a redundant statement.

**Comment by bztsrc** [comment]
It only looks like redundant, but it is not, because EMMC_INTERRUPT isn't a memory address. It is an MMIO address, which means it is backed up by an IO device that might work differently than normal RAM. For example it is pretty common for devices that the same MMIO address actually addresses two different registers: on read the status register, but on write the control register.

That statement makes sure of it that the device gets triggered, the interrupt flags flushed and ready to receive further arguments. Low-level programming is often like this.

Cheers,
bzt
